### ISSUE TITLE
[tabs] Add ability to have line extend further than the tabs in case of sticky tabs

### ISSUE THREAD

**Issue by jpzwarte** [sl-design-system/components#1044]
![CleanShot 2024-03-13 at 09 41 06@2x](https://github.com/sl-design-system/components/assets/3968/8b7123cd-a4a9-45a6-b80c-ecbee84f54fa)

Top tabs are `<dna-tab-bar>`, button tabs is `<sl-tab-group>` with some custom CSS applied:

```css
sl-tab-group {
  // This makes the component occupy the full width in the page layout grid
  grid-column: full-width;

  // This is to make the line run all the way to the page edges
  &::part(container) {
    border-bottom: var(--_border-bottom);
  }

  &::part(wrapper) {
    inline-size: 100%;
    padding-block: 0;
    margin-inline: auto;
    // Integration with `<dna-page-layout>` so it matches the responsive behavior of that component
    max-inline-size: var(--dna-page-layout-max-width);
    padding-inline: var(--dna-page-layout-min-spacing);
  }

  // Remove the original line
  &::part(tab-list) {
    border-bottom: 0;
  }
}
```
